<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="node_modules\**\*"/>
        <Content Remove="node_modules\**\*"/>
        <EmbeddedResource Remove="node_modules\**\*"/>
        <None Remove="node_modules\**\*"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Asynkron.JsEngine\Asynkron.JsEngine.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="scripts\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
