// <auto-generated />
using System.Text;

namespace Asynkron.JsEngine.StdLib;

internal static class StringUnicodeCaseMappings
{
    internal static bool TryGetSpecialLowercase(Rune rune, out string mapped)
    {
        switch (rune.Value)
        {
            case 0x130: mapped = "i\u0307"; return true;
            case 0x1F88: mapped = "\u1f80"; return true;
            case 0x1F89: mapped = "\u1f81"; return true;
            case 0x1F8A: mapped = "\u1f82"; return true;
            case 0x1F8B: mapped = "\u1f83"; return true;
            case 0x1F8C: mapped = "\u1f84"; return true;
            case 0x1F8D: mapped = "\u1f85"; return true;
            case 0x1F8E: mapped = "\u1f86"; return true;
            case 0x1F8F: mapped = "\u1f87"; return true;
            case 0x1F98: mapped = "\u1f90"; return true;
            case 0x1F99: mapped = "\u1f91"; return true;
            case 0x1F9A: mapped = "\u1f92"; return true;
            case 0x1F9B: mapped = "\u1f93"; return true;
            case 0x1F9C: mapped = "\u1f94"; return true;
            case 0x1F9D: mapped = "\u1f95"; return true;
            case 0x1F9E: mapped = "\u1f96"; return true;
            case 0x1F9F: mapped = "\u1f97"; return true;
            case 0x1FA8: mapped = "\u1fa0"; return true;
            case 0x1FA9: mapped = "\u1fa1"; return true;
            case 0x1FAA: mapped = "\u1fa2"; return true;
            case 0x1FAB: mapped = "\u1fa3"; return true;
            case 0x1FAC: mapped = "\u1fa4"; return true;
            case 0x1FAD: mapped = "\u1fa5"; return true;
            case 0x1FAE: mapped = "\u1fa6"; return true;
            case 0x1FAF: mapped = "\u1fa7"; return true;
            case 0x1FBC: mapped = "\u1fb3"; return true;
            case 0x1FCC: mapped = "\u1fc3"; return true;
            case 0x1FFC: mapped = "\u1ff3"; return true;
            default: mapped = string.Empty; return false;
        }
    }

    internal static bool TryGetSpecialUppercase(Rune rune, out string mapped)
    {
        switch (rune.Value)
        {
            case 0xDF: mapped = "SS"; return true;
            case 0xFB00: mapped = "FF"; return true;
            case 0xFB01: mapped = "FI"; return true;
            case 0xFB02: mapped = "FL"; return true;
            case 0xFB03: mapped = "FFI"; return true;
            case 0xFB04: mapped = "FFL"; return true;
            case 0xFB05: mapped = "ST"; return true;
            case 0xFB06: mapped = "ST"; return true;
            case 0x587: mapped = "\u0535\u0552"; return true;
            case 0xFB13: mapped = "\u0544\u0546"; return true;
            case 0xFB14: mapped = "\u0544\u0535"; return true;
            case 0xFB15: mapped = "\u0544\u053b"; return true;
            case 0xFB16: mapped = "\u054e\u0546"; return true;
            case 0xFB17: mapped = "\u0544\u053d"; return true;
            case 0x149: mapped = "\u02bcN"; return true;
            case 0x390: mapped = "\u0399\u0308\u0301"; return true;
            case 0x3B0: mapped = "\u03a5\u0308\u0301"; return true;
            case 0x1F0: mapped = "J\u030c"; return true;
            case 0x1E96: mapped = "H\u0331"; return true;
            case 0x1E97: mapped = "T\u0308"; return true;
            case 0x1E98: mapped = "W\u030a"; return true;
            case 0x1E99: mapped = "Y\u030a"; return true;
            case 0x1E9A: mapped = "A\u02be"; return true;
            case 0x1F50: mapped = "\u03a5\u0313"; return true;
            case 0x1F52: mapped = "\u03a5\u0313\u0300"; return true;
            case 0x1F54: mapped = "\u03a5\u0313\u0301"; return true;
            case 0x1F56: mapped = "\u03a5\u0313\u0342"; return true;
            case 0x1FB6: mapped = "\u0391\u0342"; return true;
            case 0x1FC6: mapped = "\u0397\u0342"; return true;
            case 0x1FD2: mapped = "\u0399\u0308\u0300"; return true;
            case 0x1FD3: mapped = "\u0399\u0308\u0301"; return true;
            case 0x1FD6: mapped = "\u0399\u0342"; return true;
            case 0x1FD7: mapped = "\u0399\u0308\u0342"; return true;
            case 0x1FE2: mapped = "\u03a5\u0308\u0300"; return true;
            case 0x1FE3: mapped = "\u03a5\u0308\u0301"; return true;
            case 0x1FE4: mapped = "\u03a1\u0313"; return true;
            case 0x1FE6: mapped = "\u03a5\u0342"; return true;
            case 0x1FE7: mapped = "\u03a5\u0308\u0342"; return true;
            case 0x1FF6: mapped = "\u03a9\u0342"; return true;
            case 0x1F80: mapped = "\u1f08\u0399"; return true;
            case 0x1F81: mapped = "\u1f09\u0399"; return true;
            case 0x1F82: mapped = "\u1f0a\u0399"; return true;
            case 0x1F83: mapped = "\u1f0b\u0399"; return true;
            case 0x1F84: mapped = "\u1f0c\u0399"; return true;
            case 0x1F85: mapped = "\u1f0d\u0399"; return true;
            case 0x1F86: mapped = "\u1f0e\u0399"; return true;
            case 0x1F87: mapped = "\u1f0f\u0399"; return true;
            case 0x1F88: mapped = "\u1f08\u0399"; return true;
            case 0x1F89: mapped = "\u1f09\u0399"; return true;
            case 0x1F8A: mapped = "\u1f0a\u0399"; return true;
            case 0x1F8B: mapped = "\u1f0b\u0399"; return true;
            case 0x1F8C: mapped = "\u1f0c\u0399"; return true;
            case 0x1F8D: mapped = "\u1f0d\u0399"; return true;
            case 0x1F8E: mapped = "\u1f0e\u0399"; return true;
            case 0x1F8F: mapped = "\u1f0f\u0399"; return true;
            case 0x1F90: mapped = "\u1f28\u0399"; return true;
            case 0x1F91: mapped = "\u1f29\u0399"; return true;
            case 0x1F92: mapped = "\u1f2a\u0399"; return true;
            case 0x1F93: mapped = "\u1f2b\u0399"; return true;
            case 0x1F94: mapped = "\u1f2c\u0399"; return true;
            case 0x1F95: mapped = "\u1f2d\u0399"; return true;
            case 0x1F96: mapped = "\u1f2e\u0399"; return true;
            case 0x1F97: mapped = "\u1f2f\u0399"; return true;
            case 0x1F98: mapped = "\u1f28\u0399"; return true;
            case 0x1F99: mapped = "\u1f29\u0399"; return true;
            case 0x1F9A: mapped = "\u1f2a\u0399"; return true;
            case 0x1F9B: mapped = "\u1f2b\u0399"; return true;
            case 0x1F9C: mapped = "\u1f2c\u0399"; return true;
            case 0x1F9D: mapped = "\u1f2d\u0399"; return true;
            case 0x1F9E: mapped = "\u1f2e\u0399"; return true;
            case 0x1F9F: mapped = "\u1f2f\u0399"; return true;
            case 0x1FA0: mapped = "\u1f68\u0399"; return true;
            case 0x1FA1: mapped = "\u1f69\u0399"; return true;
            case 0x1FA2: mapped = "\u1f6a\u0399"; return true;
            case 0x1FA3: mapped = "\u1f6b\u0399"; return true;
            case 0x1FA4: mapped = "\u1f6c\u0399"; return true;
            case 0x1FA5: mapped = "\u1f6d\u0399"; return true;
            case 0x1FA6: mapped = "\u1f6e\u0399"; return true;
            case 0x1FA7: mapped = "\u1f6f\u0399"; return true;
            case 0x1FA8: mapped = "\u1f68\u0399"; return true;
            case 0x1FA9: mapped = "\u1f69\u0399"; return true;
            case 0x1FAA: mapped = "\u1f6a\u0399"; return true;
            case 0x1FAB: mapped = "\u1f6b\u0399"; return true;
            case 0x1FAC: mapped = "\u1f6c\u0399"; return true;
            case 0x1FAD: mapped = "\u1f6d\u0399"; return true;
            case 0x1FAE: mapped = "\u1f6e\u0399"; return true;
            case 0x1FAF: mapped = "\u1f6f\u0399"; return true;
            case 0x1FB3: mapped = "\u0391\u0399"; return true;
            case 0x1FBC: mapped = "\u0391\u0399"; return true;
            case 0x1FC3: mapped = "\u0397\u0399"; return true;
            case 0x1FCC: mapped = "\u0397\u0399"; return true;
            case 0x1FF3: mapped = "\u03a9\u0399"; return true;
            case 0x1FFC: mapped = "\u03a9\u0399"; return true;
            case 0x1FB2: mapped = "\u1fba\u0399"; return true;
            case 0x1FB4: mapped = "\u0386\u0399"; return true;
            case 0x1FC2: mapped = "\u1fca\u0399"; return true;
            case 0x1FC4: mapped = "\u0389\u0399"; return true;
            case 0x1FF2: mapped = "\u1ffa\u0399"; return true;
            case 0x1FF4: mapped = "\u038f\u0399"; return true;
            case 0x1FB7: mapped = "\u0391\u0342\u0399"; return true;
            case 0x1FC7: mapped = "\u0397\u0342\u0399"; return true;
            case 0x1FF7: mapped = "\u03a9\u0342\u0399"; return true;
            default: mapped = string.Empty; return false;
        }
    }

    internal static bool IsSoftDotted(Rune rune)
    {
        return rune.Value switch
        {
            >= 0x69 and <= 0x6A => true,
            0x12F => true,
            0x249 => true,
            0x268 => true,
            0x29D => true,
            0x2B2 => true,
            0x3F3 => true,
            0x456 => true,
            0x458 => true,
            0x1D62 => true,
            0x1D96 => true,
            0x1DA4 => true,
            0x1DA8 => true,
            0x1E2D => true,
            0x1ECB => true,
            0x2071 => true,
            >= 0x2148 and <= 0x2149 => true,
            0x2C7C => true,
            >= 0x1D422 and <= 0x1D423 => true,
            >= 0x1D456 and <= 0x1D457 => true,
            >= 0x1D48A and <= 0x1D48B => true,
            >= 0x1D4BE and <= 0x1D4BF => true,
            >= 0x1D4F2 and <= 0x1D4F3 => true,
            >= 0x1D526 and <= 0x1D527 => true,
            >= 0x1D55A and <= 0x1D55B => true,
            >= 0x1D58E and <= 0x1D58F => true,
            >= 0x1D5C2 and <= 0x1D5C3 => true,
            >= 0x1D5F6 and <= 0x1D5F7 => true,
            >= 0x1D62A and <= 0x1D62B => true,
            >= 0x1D65E and <= 0x1D65F => true,
            >= 0x1D692 and <= 0x1D693 => true,
            0x1DF1A => true,
            >= 0x1E04C and <= 0x1E04D => true,
            0x1E068 => true,
            _ => false
        };
    }
}
