#!/usr/bin/env python3
"""Generate ECMAScript string Unicode case-mapping helpers from SpecialCasing.txt."""

from pathlib import Path
import urllib.request

UNICODE_VERSION = "16.0.0"
BASE_URL = f"https://www.unicode.org/Public/{UNICODE_VERSION}/ucd"
OUTPUT_FILE = Path(__file__).resolve().parent.parent / "src" / "Asynkron.JsEngine" / "StdLib" / "String" / "StringUnicodeCaseMappings.generated.cs"


def main() -> None:
    special_casing = urllib.request.urlopen(f"{BASE_URL}/SpecialCasing.txt", timeout=20).read().decode("utf-8")
    prop_list = urllib.request.urlopen(f"{BASE_URL}/PropList.txt", timeout=20).read().decode("utf-8")
    lower_entries: list[tuple[int, str]] = []
    upper_entries: list[tuple[int, str]] = []
    soft_dotted_ranges: list[tuple[int, int]] = []
    for line in special_casing.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = [p.strip() for p in line.split(";")]
        if len(parts) < 5:
            continue
        code, lower, _title, upper, condition = parts[:5]
        if condition:
            continue
        codepoint = int(code, 16)
        if lower.replace(" ", "") != code.replace(" ", ""):
            mapped = "".join(chr(int(value, 16)) for value in lower.split())
            escaped = mapped.encode("unicode_escape").decode("ascii").replace('"', '\\"')
            lower_entries.append((codepoint, escaped))
        if upper.replace(" ", "") != code.replace(" ", ""):
            mapped = "".join(chr(int(value, 16)) for value in upper.split())
            escaped = mapped.encode("unicode_escape").decode("ascii").replace('"', '\\"')
            upper_entries.append((codepoint, escaped))

    for line in prop_list.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = [p.strip() for p in line.split(";")]
        if len(parts) < 2 or parts[1] != "Soft_Dotted":
            continue
        if ".." in parts[0]:
            start_hex, end_hex = parts[0].split("..", 1)
            soft_dotted_ranges.append((int(start_hex, 16), int(end_hex, 16)))
        else:
            value = int(parts[0], 16)
            soft_dotted_ranges.append((value, value))

    lines = [
        "// <auto-generated />",
        "using System.Text;",
        "",
        "namespace Asynkron.JsEngine.StdLib;",
        "",
        "internal static class StringUnicodeCaseMappings",
        "{",
        "    internal static bool TryGetSpecialLowercase(Rune rune, out string mapped)",
        "    {",
        "        switch (rune.Value)",
        "        {",
    ]
    for codepoint, escaped in lower_entries:
        lines.append(f'            case 0x{codepoint:X}: mapped = "{escaped}"; return true;')
    lines.extend([
        "            default: mapped = string.Empty; return false;",
        "        }",
        "    }",
        "",
        "    internal static bool TryGetSpecialUppercase(Rune rune, out string mapped)",
        "    {",
        "        switch (rune.Value)",
        "        {",
    ])
    for codepoint, escaped in upper_entries:
        lines.append(f'            case 0x{codepoint:X}: mapped = "{escaped}"; return true;')
    lines.extend([
        "            default: mapped = string.Empty; return false;",
        "        }",
        "    }",
        "",
        "    internal static bool IsSoftDotted(Rune rune)",
        "    {",
        "        return rune.Value switch",
        "        {",
    ])
    for start, end in soft_dotted_ranges:
        if start == end:
            lines.append(f"            0x{start:X} => true,")
        else:
            lines.append(f"            >= 0x{start:X} and <= 0x{end:X} => true,")
    lines.extend([
        "            _ => false",
        "        };",
        "    }",
        "}",
        "",
    ])
    OUTPUT_FILE.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
